### ISSUE TITLE
Does not cover ACL calls

### ISSUE THREAD

**Issue by ChrisCrewdson** [ianakelly/Invoke#1]
I am trying to use the ACL calls on this API (like /api/Dcm/ACL/authenticate) and I get back maybe what is referred to elsewhere as a "security token", but I cannot determine how to use it:
{
     "id":"731343...deleted...C110003",
     "created":"2015-03-12T21:47:59.148+0000",
     "expires":null
}
I deleted the chunk from the middle of the ID for security sake, just in case.

**Comment by ChrisCrewdson** [comment]
I am getting an "Authorization failed" message on all of these examples on my server:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ca.com/lisa/invoke/v2.0 Error.xsd" type="application/vnd.ca.lisaInvoke.error+xml" xmlns="http://www.ca.com/lisa/invoke/v2.0">
<Id>4200</Id>
<Message>Authorization failed</Message>
</Error>
```

**Comment by rafaeloltra** [comment]
Hey Chris, I haven't had a chance to go over the docs, but I believe the way the REST API (Invoke 2) expects authentication to happen is using the basic authentication.

Try this approach, instead of hitting the ACL resource, hit whatever resource you are interested (as long as your user is allowed to access it obviously) and add a HTTP header called "Authorization", the value of the header should be: "Basic username:password in a base64 encoding"

so for instance for user and password admin the header Authorization should have the value: "Basic YWRtaW46YWRtaW4="

Let me know if this work for you, I'll try it on my environment also when I get a chance.

thanks

Rafael

**Comment by ChrisCrewdson** [comment]
This is the breakthrough I made this morning, so I am now ignoring the ACL calls and just using basic auth. I didn't see the basic auth suggestion anywhere in the docs, so I just didn't think of it.
It seems to work great.
